name: flutter_shaders_com
description: Website for exploring Flutter shaders
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  static_shock:
    git:
      url: https://github.com/Flutter-Bounty-Hunters/static_shock/
      path: packages/static_shock
      ref: 145_add-tailwind-css-support

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
